project:
  type: website
  output-dir: docs

website:
  title: "diginsight blog"
  description: "blog about diginsight components, samples and tools"
  margin-header: subscribe.html
  # site-url: https://www.myblogexample.io
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml      
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: floating
    search: true
format:
  html:
    theme:
      - cosmo
      - styles/theme.scss
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github



