project:
  type: website


website:
  title: "diginsight blog"
  description: "blog about diginsight components, samples and tools"
  margin-header: subscribe.html
  # site-url: https://www.myblogexample.io
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml      
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



